#!/bin/bash
set -e

# common stuff between install/update

echo "install/update jsonnet-language-server"
go install github.com/grafana/jsonnet-language-server@latest

echo "install/update phpactor"
TARGET_DIR="$HOME/git/phpactor"
git -C "$TARGET_DIR" pull || git clone  git@github.com:phpactor/phpactor" $TARGET_DIR"
cd "$TARGET_DIR"
composer install
cd -
ln -snf "$TARGET_DIR/bin/phpactor" "$HOME/bin/phpactor"
