#!/bin/bash

echo "ubuntu: installing some LSPs"
npm i -g typescript typescript-language-server
npm i -g vim-language-server
npm i -g bash-language-server
npm i -g @ansible/ansible-language-server


sudo apt install -y php8.2 \
php8.2-gettext \
php8.2-gd \
php8.2-pgsql \
php8.2-redis \
php8.2-xml \
php8.2-zip \
php8.2-curl \
build-essential \
curl git xclip \
cargo \
clangd \
shellcheck \
ripgrep \
libssl-dev \
protobuf-compiler

sudo snap install --classic pyright

/install-go


# mkdir -p "$HOME/.lua-language-server"
# curl -s -L https://github.com/LuaLS/lua-language-server/releases/download/3.6.18/lua-language-server-3.6.18-linux-x64.tar.gz | tar xvz -C "$HOME/.lua-language-server"
# TODO
# #!/bin/bash 
# exec "<path-to-directory>/bin/lua-language-server" "$@"
