#!/bin/bash
echo "Git pull"
git pull
echo "Git submodule init"
git submodule init
echo "Git submodule update"
git submodule update
#git submodule update
git submodule foreach git pull origin master

cd dot-vim
./install
