#!/bin/bash

echo "ubuntu: install nvm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

nvm install "lts/*"

echo "ubuntu: installing some LSPs"
npm i -g typescript typescript-language-server
npm i -g vim-language-server
npm i -g bash-language-server
npm i -g @ansible/ansible-language-server


sudo apt install -y php8.2 \
php8.2-gettext \
php8.2-gd \
php8.2-pgsql \
php8.2-redis \
php8.2-xml \
php8.2-zip \
php8.2-curl \
build-essential \
curl git xclip \
cargo \
clangd \
shellcheck \
ripgrep \
libssl-dev \
protobuf-compiler

sudo snap install --classic pyright

# upgade go 
VERSION=$(curl -s https://go.dev/dl/?mode=json | jq -r '.[0].version')
CURRENTVERSION=$(go version|cut -d' ' -f 3)
if [[ $VERSION == "$CURRENTVERSION" ]]; then
	echo "latest go release already installed: $VERSION"
else
	echo "upgrade go version to $VERSION"
	wget -P /tmp/ "https://storage.googleapis.com/golang/$VERSION.linux-amd64.tar.gz"
	sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf "/tmp/$VERSION.linux-amd64.tar.gz"
	rm "/tmp/$VERSION.linux-amd64.tar.gz"
fi



# mkdir -p "$HOME/.lua-language-server"
# curl -s -L https://github.com/LuaLS/lua-language-server/releases/download/3.6.18/lua-language-server-3.6.18-linux-x64.tar.gz | tar xvz -C "$HOME/.lua-language-server"
# TODO
# #!/bin/bash 
# exec "<path-to-directory>/bin/lua-language-server" "$@"
