#!/bin/bash

echo "ubuntu: install nvm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

nvm install "lts/*"

echo "ubuntu: installing some LSPs"
npm i -g typescript typescript-language-server
npm i -g vim-language-server
npm i -g bash-language-server
npm i -g @ansible/ansible-language-server


#php stuff
sudo apt install -y php8.2 -y
sudo apt install -y php8.2-gettext
sudo apt install -y php8.2-gd
sudo apt install -y php8.2-pgsql
sudo apt install -y php8.2-redis
sudo apt install -y php8.2-xml
sudo apt install -y php8.2-zip
sudo apt install -y php8.2-curl

sudo apt instlal -y build-essential
sudo apt install -y curl git xclip
sudo apt install -y cargo
sudo apt install -y clangd
sudo apt install -y shellcheck
sudo apt install -y ripgrep
sudo apt install -y libssl-dev
sudo apt install -y protobuf-compiler
sudo snap install --classic pyright

# mkdir -p "$HOME/.lua-language-server"
# curl -s -L https://github.com/LuaLS/lua-language-server/releases/download/3.6.18/lua-language-server-3.6.18-linux-x64.tar.gz | tar xvz -C "$HOME/.lua-language-server"
# TODO
# #!/bin/bash 
# exec "<path-to-directory>/bin/lua-language-server" "$@"
