#!/bin/bash
set -e

# lnk "file here" "file in home"
lnk(){
	FROM=$2
	TO=$1
	if [ ! -L "$HOME/$FROM" ]; then
		echo "Creating symbolic link from $HOME/$FROM to $PWD/$TO"
		ln -s "$PWD/$TO" "$HOME/$FROM"
	fi
}

i(){
	if ! [ -x "$(command -v pacman)" ]; then
	  echo "pacman not found. skipping install of $@"
	  return
	fi
	sudo pacman -S --needed "$@"
}

echo "Install arch pacman deps"
i neovim python-pynvim
i noto-fonts-cjk noto-fonts-emoji noto-fonts-extra ttf-bitstream-vera ttf-croscore ttf-dejavu ttf-hack ttf-roboto ttf-hack #fonts
i vint # ale linter for vim config
i extra/php-intl # deps for phpactor
i prettier # json js tsx formatter
i yarn
i ansible-lint
i git-delta
i alacritty
i ripgrep fd
i bash-language-server

echo "Git pull"
git pull --autostash

echo "Setting up bashrc"
git config --global credential.helper 'cache --timeout 3600'
grep -q ". $PWD/bashrc" ~/.bashrc || echo ". $PWD/bashrc" >> ~/.bashrc

if [ ! -f ~/bin/kube-ps1.sh ]; then
	echo "Install kube-ps1"
	curl -s -o ~/bin/kube-ps1.sh https://raw.githubusercontent.com/jonmosco/kube-ps1/master/kube-ps1.sh
fi

mkdir -p ~/.vim/bundle

if [ ! -d ~/.fzf ]; then
	git clone https://github.com/junegunn/fzf.git ~/.fzf
	~/.fzf/install --all
fi

lnk "jshintrc" ".jshintrc"
lnk "lockFuzzy" "bin/lockFuzzy"
lnk "phpmd-ruleset.xml" ".phpmd-ruleset.xml"
lnk "dir_colors" ".dir_colors"
lnk "nvim" ".config/nvim"
lnk "alacritty" ".config/alacritty"

echo "Installing plugins into vim"
nvim +PlugInstall +qall

#must be after PlugInstall since we want newer golangci-lint than :GoInstallBinaries provide
if [ ! -f ~/go/bin/golangci-lint ]; then
	echo "Install golangci-lint"
	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
fi

echo "done"
